### ISSUE TITLE
vue warn and error in electron project

### ISSUE THREAD

**Issue by Fauny** [lindell/vue-barcode#13]
```log
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Barcode>
       <Modal>
         <Card>
```

and this:

```
TypeError: this.$el.querySelector is not a function
    at VueComponent.render (/Users/Fauny/Work/WoodManager/source/epacial-vid/node_modules/vue-barcode/index.js:72:22)
    at VueComponent.Vue.$watch (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3606:10)
    at VueComponent.mounted (/Users/Fauny/Work/WoodManager/source/epacial-vid/node_modules/vue-barcode/index.js:35:10)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2916:21)
    at Object.insert (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4149:7)
    at invokeInsertHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5944:28)
    at Vue.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6163:5)
    at Vue._update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2665:19)
    at Vue.updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2783:10)
    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3137:25)
```

**Comment by Fauny** [comment]
sorry, this is a vue~electron~webpack issue, pls close it

**Comment by duckbrain** [comment]
@Fauny Do you have a link/resolution? I'm experiencing this issue too.

**Comment by Fauny** [comment]
@duckbrain : (
I had to use jsbarcode instead. and embed vue-barcode code in my project
